AMQP_URI: ${QUEUE_HOST}

DB_URIS: 
  "command_famous:Base": ${COMMANDDB_HOST} 

LOGGING:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
  
  root:
    level: DEBUG
    handlers: [console]
